### ISSUE TITLE
Select Image

### ISSUE THREAD

**Issue by tiagolagrecap** [Pierre-Sassoulas/django-survey#133] opened 2021-04-01 11:52 UTC
Hi, im trying to use the option Select Image, but not working, i got this error.

'ImageSelectWidget' object has no attribute 'template_name'

Anyone can help me?
Thanks.

**Comment by Pierre-Sassoulas** [comment] 2021-04-01 11:59
Duplicate of #115

**Closed by Pierre-Sassoulas** 2021-04-01 11:59 UTC

**Comment by tiagolagrecap** [comment] 2021-04-01 12:03
Closed, but still a not working.

tks.

**Comment by Pierre-Sassoulas** [comment] 2021-04-01 12:07
You can still participate in the other issue, ask questions showing what you did, open a merge request fixing the problem, open a bounty on issue hunt so someone else fix the problem...  Opening a duplicate ticket with less content is not going to help.
