### ISSUE TITLE
Select widget problem 

### ISSUE THREAD

**Issue by florianmouchantaf** [Pierre-Sassoulas/django-survey#47] opened 2019-09-18 10:07 UTC
Hi,

I'm a new user of django-survey. I encountered a problem in displaying a question type select . As i understood, the form.select widget would make the html code  but in my case the html code of a question type select in the form doesn't contain <select> tag, so it dipslay the choices as options without a dropdown list.  I can't seem to resolve the problem.

Thanks for the help !

**Comment by Pierre-Sassoulas** [comment] 2019-09-19 13:00
I think it's a duplicate of #11. Sorry, I don't have a lot of time for this project right now except for low effort maintenance. if you want to fix the problem yourself, feel free to make a pull request. It might work by replacing almost everything in `survey/templates/survey/question.html` by `{{form|boootstrap}}` using django-bootstrap-form. See the project with an example here: https://github.com/tzangms/django-bootstrap-form.

**Closed by Pierre-Sassoulas** 2019-09-19 13:00 UTC
Labels: duplicate

**Comment by florianmouchantaf** [comment] 2019-09-19 14:39
I used django-boostrap-form but the issue is that each question is duplicated and the second time it is displayed with tag written from admin page . If there is a possible fix to it thanks for the help .
________________________________

**Comment by Pierre-Sassoulas** [comment] 2019-09-19 22:05
Probably the same thing than here : https://github.com/Pierre-Sassoulas/django-survey/pull/46#discussion_r308914216

**Comment by florianmouchantaf** [comment] 2019-09-20 07:24
I maintained the category condition and field required but the problem is that each question is duplicated and it doesn't seems to be a problem in the template question.html. Maybe in bootstrap form ?
________________________________

**Comment by florianmouchantaf** [comment] 2019-09-20 11:32
En fair comment on utilise boostrap et safe en meme temps car si j'enlève la balise form.label |safe   et je garde form|boostrap   alors les balises restent presentent ne sont pas interpretées par boostrap.

On 20 Sep 2019 00:05, Pierre Sassoulas <notifications@github.com> wrote:

Probably the same thing than here : #46 (comment)<https://github.com/Pierre-Sassoulas/django-survey/pull/46#discussion_r308914216>

**Comment by Pierre-Sassoulas** [comment] 2019-09-20 19:34
I think we can't use both in the template, we probably need to do one of those treatments it in python. (I might be wrong, not touched django for a long time)
